server:
  port: 8088

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/airplane?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 52912615

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

